[theme]
primaryColor = "#0145e4"               # bleu Ã©lectrique
backgroundColor = "#ffffff"            # fond blanc
secondaryBackgroundColor = "#e6f0ff"   # panels / sidebar bleu clair
textColor = "#000000"                   # texte noir
font = "sans serif"
